version: '2.1'
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - snyk/scan:
          additional-arguments: "code"
workflows: null